/**
 * Rust code generation for custom Soroban policy contracts.
 *
 * All generated contracts use the real OZ Accounts policy interface:
 *   install(env, install_params, context_rule: ContextRule, smart_account: Address)
 *   enforce(env, context: Context, signers: Vec<Signer>, context_rule, smart_account)
 *   uninstall(env, context_rule, smart_account)
 *   can_enforce(...) -> bool       — read-only pre-check
 *
 * DataKey uses u32 (context_rule.id), not BytesN<32>.
 * No require_auth in install/uninstall — OZ smart account handles it.
 * Error handling via policy_panic(&env, PolicyError::X).
 */

import type { PolicySpec, RustPolicySource } from './types.js';
import type { TimeBoundConfig, CallFilterConfig, FrequencyLimitConfig } from './types.js';

// ---------------------------------------------------------------------------
// Time-Bound policy generator
// ---------------------------------------------------------------------------

export function generateTimeBoundSource(spec: PolicySpec): RustPolicySource {
  const config = spec.config as TimeBoundConfig;
  const name = spec.contractName ?? 'policy_time_bound';

  const source = `//! Generated Time-Bound Policy
//! Start ledger: ${config.startLedger}
//! End ledger:   ${config.endLedger}
//!
//! Allows invocations only when the current ledger sequence is within
//! [start_ledger, end_ledger] (inclusive).
//!
//! GENERATED BY OZ POLICY BUILDER — REVIEW BEFORE DEPLOYING.

#![no_std]

use oz_policy_trait::{policy_panic, ContextRule, PolicyError, Signer};
use soroban_sdk::{auth::Context, contract, contractimpl, contracttype, Address, Env, Vec};

// ── Params ────────────────────────────────────────────────────────────────────

#[contracttype]
pub struct TimeBoundParams {
    pub start_ledger: u32,
    pub end_ledger: u32,
}

// ── Storage ───────────────────────────────────────────────────────────────────

#[contracttype]
pub struct TimeBoundConfig {
    pub start_ledger: u32,
    pub end_ledger: u32,
}

#[contracttype]
pub enum DataKey {
    Config(Address, u32),
}

// ── Contract ──────────────────────────────────────────────────────────────────

#[contract]
pub struct ${toCamelCase(name)};

#[contractimpl]
impl ${toCamelCase(name)} {
    pub fn install(
        env: Env,
        install_params: TimeBoundParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        if install_params.start_ledger > install_params.end_ledger {
            policy_panic(&env, PolicyError::InvalidConfig);
        }
        let cfg = TimeBoundConfig {
            start_ledger: install_params.start_ledger,
            end_ledger: install_params.end_ledger,
        };
        env.storage()
            .persistent()
            .set(&DataKey::Config(smart_account, context_rule.id), &cfg);
    }

    pub fn enforce(
        env: Env,
        _context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        let cfg: TimeBoundConfig = env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule.id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled));

        let seq = env.ledger().sequence();
        if seq < cfg.start_ledger || seq > cfg.end_ledger {
            policy_panic(&env, PolicyError::TimeWindowViolation);
        }
    }

    pub fn uninstall(env: Env, context_rule: ContextRule, smart_account: Address) {
        env.storage()
            .persistent()
            .remove(&DataKey::Config(smart_account, context_rule.id));
    }

    pub fn can_enforce(env: Env, context_rule: ContextRule, smart_account: Address) -> bool {
        let cfg: TimeBoundConfig = match env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule.id))
        {
            Some(c) => c,
            None => return false,
        };
        let seq = env.ledger().sequence();
        seq >= cfg.start_ledger && seq <= cfg.end_ledger
    }

    pub fn get_config(env: Env, context_rule_id: u32, smart_account: Address) -> TimeBoundConfig {
        env.storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule_id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled))
    }
}
`;

  return {
    contractName: name,
    filename: `${name}/src/lib.rs`,
    source,
    cargoToml: generateCargoToml(name),
  };
}

// ---------------------------------------------------------------------------
// Call-Filter policy generator
// ---------------------------------------------------------------------------

export function generateCallFilterSource(spec: PolicySpec): RustPolicySource {
  const config = spec.config as CallFilterConfig;
  const name = spec.contractName ?? 'policy_call_filter';

  const source = `//! Generated Call Filter Policy
//!
//! Allowed calls:
${config.allowedCalls.map((c) => `//!   - ${sanitizeForComment(c.contractId)}::${sanitizeForComment(c.functionName)}`).join('\n')}
//!
//! Supports typed argument constraints:
//!   ExactAddress(pos, addr)  — arg at position must equal address
//!   ExactValue(pos, val)     — arg at position must equal i128
//!   AmountMax(pos, max)      — arg must be <= max
//!   AmountMin(pos, min)      — arg must be >= min
//!
//! GENERATED BY OZ POLICY BUILDER — REVIEW BEFORE DEPLOYING.

#![no_std]

use oz_policy_trait::{policy_panic, ContextRule, PolicyError, Signer};
use soroban_sdk::{
    auth::{Context, ContractContext},
    contract, contractimpl, contracttype, Address, Env, TryFromVal, Vec,
};

// ── Types ─────────────────────────────────────────────────────────────────────

#[contracttype]
pub enum ArgConstraint {
    ExactAddress(u32, Address),
    ExactValue(u32, i128),
    AmountMax(u32, i128),
    AmountMin(u32, i128),
}

#[contracttype]
pub struct AllowedCall {
    pub contract: Address,
    pub fn_name: soroban_sdk::Symbol,
    pub arg_constraints: Vec<ArgConstraint>,
}

#[contracttype]
pub struct CallFilterParams {
    pub allowed_calls: Vec<AllowedCall>,
}

#[contracttype]
pub struct CallFilterConfig {
    pub allowed_calls: Vec<AllowedCall>,
}

#[contracttype]
pub enum DataKey {
    Config(Address, u32),
}

// ── Contract ──────────────────────────────────────────────────────────────────

#[contract]
pub struct ${toCamelCase(name)};

#[contractimpl]
impl ${toCamelCase(name)} {
    pub fn install(
        env: Env,
        install_params: CallFilterParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        if install_params.allowed_calls.is_empty() {
            policy_panic(&env, PolicyError::InvalidConfig);
        }
        let cfg = CallFilterConfig { allowed_calls: install_params.allowed_calls };
        env.storage()
            .persistent()
            .set(&DataKey::Config(smart_account, context_rule.id), &cfg);
    }

    pub fn enforce(
        env: Env,
        context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        let cfg: CallFilterConfig = env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule.id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled));

        if !is_allowed(&env, &cfg, &context) {
            policy_panic(&env, PolicyError::ScopeViolation);
        }
    }

    pub fn uninstall(env: Env, context_rule: ContextRule, smart_account: Address) {
        env.storage()
            .persistent()
            .remove(&DataKey::Config(smart_account, context_rule.id));
    }

    pub fn can_enforce(
        env: Env,
        context: Context,
        context_rule: ContextRule,
        smart_account: Address,
    ) -> bool {
        let cfg: CallFilterConfig = match env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule.id))
        {
            Some(c) => c,
            None => return false,
        };
        is_allowed(&env, &cfg, &context)
    }

    pub fn get_config(env: Env, context_rule_id: u32, smart_account: Address) -> CallFilterConfig {
        env.storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule_id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled))
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn is_allowed(env: &Env, cfg: &CallFilterConfig, context: &Context) -> bool {
    let ctx: &ContractContext = match context {
        Context::Contract(c) => c,
        _ => return false,
    };
    for i in 0..cfg.allowed_calls.len() {
        let allowed = cfg.allowed_calls.get(i).unwrap();
        if allowed.contract == ctx.contract && allowed.fn_name == ctx.fn_name {
            if constraints_pass(env, &allowed.arg_constraints, ctx) {
                return true;
            }
        }
    }
    false
}

fn constraints_pass(env: &Env, constraints: &Vec<ArgConstraint>, ctx: &ContractContext) -> bool {
    for i in 0..constraints.len() {
        match constraints.get(i).unwrap() {
            ArgConstraint::ExactAddress(pos, required) => {
                let v = match ctx.args.get(pos) { Some(v) => v, None => return false };
                match Address::try_from_val(env, &v) {
                    Ok(a) if a == required => {}
                    _ => return false,
                }
            }
            ArgConstraint::ExactValue(pos, required) => {
                let v = match ctx.args.get(pos) { Some(v) => v, None => return false };
                match i128::try_from_val(env, &v) {
                    Ok(n) if n == required => {}
                    _ => return false,
                }
            }
            ArgConstraint::AmountMax(pos, max) => {
                let v = match ctx.args.get(pos) { Some(v) => v, None => return false };
                match i128::try_from_val(env, &v) {
                    Ok(n) if n <= max => {}
                    _ => return false,
                }
            }
            ArgConstraint::AmountMin(pos, min) => {
                let v = match ctx.args.get(pos) { Some(v) => v, None => return false };
                match i128::try_from_val(env, &v) {
                    Ok(n) if n >= min => {}
                    _ => return false,
                }
            }
        }
    }
    true
}
`;

  return {
    contractName: name,
    filename: `${name}/src/lib.rs`,
    source,
    cargoToml: generateCargoToml(name),
  };
}

// ---------------------------------------------------------------------------
// Frequency-Limit policy generator
// ---------------------------------------------------------------------------

export function generateFrequencyLimitSource(spec: PolicySpec): RustPolicySource {
  const config = spec.config as FrequencyLimitConfig;
  const name = spec.contractName ?? 'policy_frequency_limit';

  const source = `//! Generated Frequency Limit Policy
//! Max calls: ${config.maxCallsPerWindow} per ${config.windowSeconds}s window
//!
//! GENERATED BY OZ POLICY BUILDER — REVIEW BEFORE DEPLOYING.

#![no_std]

use oz_policy_trait::{policy_panic, ContextRule, PolicyError, Signer};
use soroban_sdk::{auth::Context, contract, contractimpl, contracttype, Address, Env, Vec};

// ── Params ────────────────────────────────────────────────────────────────────

#[contracttype]
pub struct FrequencyLimitParams {
    pub max_calls: u32,
    pub window_secs: u64,
}

// ── Storage ───────────────────────────────────────────────────────────────────

#[contracttype]
pub struct FrequencyConfig {
    pub max_calls: u32,
    pub window_secs: u64,
}

#[contracttype]
pub struct FrequencyState {
    pub call_count: u32,
    pub window_start: u64,
}

#[contracttype]
pub enum DataKey {
    Config(Address, u32),
    State(Address, u32),
}

// ── Contract ──────────────────────────────────────────────────────────────────

#[contract]
pub struct ${toCamelCase(name)};

#[contractimpl]
impl ${toCamelCase(name)} {
    pub fn install(
        env: Env,
        install_params: FrequencyLimitParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        if install_params.max_calls == 0 || install_params.window_secs == 0 {
            policy_panic(&env, PolicyError::InvalidConfig);
        }
        let cfg = FrequencyConfig {
            max_calls: install_params.max_calls,
            window_secs: install_params.window_secs,
        };
        env.storage()
            .persistent()
            .set(&DataKey::Config(smart_account.clone(), context_rule.id), &cfg);

        let state = FrequencyState {
            call_count: 0,
            window_start: env.ledger().timestamp(),
        };
        env.storage()
            .persistent()
            .set(&DataKey::State(smart_account, context_rule.id), &state);
    }

    pub fn enforce(
        env: Env,
        _context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        let cfg: FrequencyConfig = env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account.clone(), context_rule.id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled));

        let mut state: FrequencyState = env
            .storage()
            .persistent()
            .get(&DataKey::State(smart_account.clone(), context_rule.id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled));

        let now = env.ledger().timestamp();
        if now >= state.window_start.saturating_add(cfg.window_secs) {
            state.window_start = now;
            state.call_count = 0;
        }

        if state.call_count >= cfg.max_calls {
            policy_panic(&env, PolicyError::FrequencyLimitExceeded);
        }
        state.call_count = state
            .call_count
            .checked_add(1)
            .unwrap_or_else(|| policy_panic(&env, PolicyError::FrequencyLimitExceeded));

        env.storage()
            .persistent()
            .set(&DataKey::State(smart_account, context_rule.id), &state);
    }

    pub fn uninstall(env: Env, context_rule: ContextRule, smart_account: Address) {
        env.storage()
            .persistent()
            .remove(&DataKey::Config(smart_account.clone(), context_rule.id));
        env.storage()
            .persistent()
            .remove(&DataKey::State(smart_account, context_rule.id));
    }

    pub fn can_enforce(env: Env, context_rule: ContextRule, smart_account: Address) -> bool {
        let cfg: FrequencyConfig = match env
            .storage()
            .persistent()
            .get(&DataKey::Config(smart_account.clone(), context_rule.id))
        {
            Some(c) => c,
            None => return false,
        };
        let state: FrequencyState = match env
            .storage()
            .persistent()
            .get(&DataKey::State(smart_account, context_rule.id))
        {
            Some(s) => s,
            None => return false,
        };
        let now = env.ledger().timestamp();
        let count = if now >= state.window_start.saturating_add(cfg.window_secs) { 0_u32 } else { state.call_count };
        count < cfg.max_calls
    }

    pub fn get_config(env: Env, context_rule_id: u32, smart_account: Address) -> FrequencyConfig {
        env.storage()
            .persistent()
            .get(&DataKey::Config(smart_account, context_rule_id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled))
    }

    pub fn get_state(env: Env, context_rule_id: u32, smart_account: Address) -> FrequencyState {
        env.storage()
            .persistent()
            .get(&DataKey::State(smart_account, context_rule_id))
            .unwrap_or_else(|| policy_panic(&env, PolicyError::NotInstalled))
    }
}
`;

  return {
    contractName: name,
    filename: `${name}/src/lib.rs`,
    source,
    cargoToml: generateCargoToml(name),
  };
}

// ---------------------------------------------------------------------------
// Cargo.toml generator
// ---------------------------------------------------------------------------

function generateCargoToml(contractName: string): string {
  return `[package]
name = "${contractName}"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "22.0.1", features = [] }
oz-policy-trait = { git = "https://github.com/oz-policy-builder/oz-policy-builder", tag = "v0.1.0" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
`;
}

// ---------------------------------------------------------------------------
// Install script generator
// ---------------------------------------------------------------------------

export function generateInstallScript(
  contextRuleLabel: string,
  scope: Array<{ contractId: string; functionName: string }>,
  lifetimeSecs: number,
  standardPolicies: Array<{ kind: string; config: unknown }>,
  customPolicyAddresses: string[],
): string {
  return `/**
 * Install Script — ${contextRuleLabel}
 * GENERATED BY OZ POLICY BUILDER — REVIEW BEFORE RUNNING.
 *
 * Steps:
 *   1. Review the generated policy Rust source files above.
 *   2. Deploy any custom policy contracts and fill in their addresses below.
 *   3. Run: ts-node install.ts --account <your-smart-account-id> --network testnet
 */

import { buildAddContextRuleTx, buildPolicyExecuteTx, submitViaRelayer } from '@oz-policy-builder/policy-synthesizer/wallet';
import { Address, xdr } from '@stellar/stellar-sdk';

// TODO: fill in deployed custom policy contract addresses
const CUSTOM_POLICY_ADDRESSES: string[] = [
${customPolicyAddresses.map((a) => `  '${a}',`).join('\n')}
];

const CONTEXT_RULE_LABEL = '${contextRuleLabel}';
const LIFETIME_SECONDS = ${lifetimeSecs};
const SCOPE = ${JSON.stringify(scope, null, 2)};

async function install(smartAccountId: string, networkPassphrase: string) {
  const policyAddresses: string[] = [
    // Standard OZ policies (already deployed):
    ${standardPolicies.map((p) => `'<OZ_${p.kind.toUpperCase()}_ADDRESS>',`).join('\n    ')}
    // Custom policies (fill in after deploying):
    ...CUSTOM_POLICY_ADDRESSES,
  ];

  // Build install params for each custom policy using the typed struct approach.
  // Each policy is installed via add_policy(rule_id, policy_addr, encoded_params).
  const installParamsXdr = buildTimeBoundParamsXdr(/* fill: start_ledger, end_ledger */);

  const { hostFuncXdr, ephemeralSigner } = await buildAddContextRuleTx({
    walletContractId: smartAccountId,
    ruleName: CONTEXT_RULE_LABEL,
    targetContract: SCOPE[0]?.contractId ?? '',
    policyAddr: policyAddresses[0] ?? '',
    installParamsXdr,
    networkPassphrase,
  });

  const txHash = await submitViaRelayer(hostFuncXdr, ephemeralSigner.publicKey());
  console.log('Context rule installed. TX hash:', txHash);
}

function buildTimeBoundParamsXdr(startLedger: number, endLedger: number): string {
  // Encode TimeBoundParams as XDR ScVal struct for add_policy
  const params = xdr.ScVal.scvMap([
    new xdr.ScMapEntry({
      key: xdr.ScVal.scvSymbol('start_ledger'),
      val: xdr.ScVal.scvU32(startLedger),
    }),
    new xdr.ScMapEntry({
      key: xdr.ScVal.scvSymbol('end_ledger'),
      val: xdr.ScVal.scvU32(endLedger),
    }),
  ]);
  return params.toXDR('base64');
}

const [,, accountId, network = 'testnet'] = process.argv;
if (!accountId) {
  console.error('Usage: ts-node install.ts <smart-account-id> [network]');
  process.exit(1);
}

const PASSPHRASES: Record<string, string> = {
  mainnet: 'Public Global Stellar Network ; September 2015',
  testnet: 'Test SDF Network ; September 2015',
};

install(accountId, PASSPHRASES[network] ?? PASSPHRASES.testnet).catch(console.error);
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toCamelCase(snakeCase: string): string {
  return snakeCase
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function sanitizeForComment(s: string): string {
  return s.replace(/[\r\n\t]/g, ' ').replace(/[^\x20-\x7E]/g, '?');
}
